/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RES_H_RPCGEN
#define _RES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct response {
	char *url;
};
typedef struct response response;

#define HTTP_REQ 0x23451111
#define HTTP_REQ 1

#if defined(__STDC__) || defined(__cplusplus)
#define req 1
extern  int * req_1(response *, CLIENT *);
extern  int * req_1_svc(response *, struct svc_req *);
extern int http_req_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define req 1
extern  int * req_1();
extern  int * req_1_svc();
extern int http_req_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_response (XDR *, response*);

#else /* K&R C */
extern bool_t xdr_response ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RES_H_RPCGEN */
