/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "res.h"
#include <curl/curl.h>

void
http_req_1(char *host,char *x)
{
	CLIENT *clnt;
	int  *result_1;
	response  req_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, HTTP_REQ, HTTP_REQ, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	req_1_arg.url=x;
	printf("this is the value of x variable: %s\n",x);
	printf("this is the value of req_1_arg variable: %s\n",req_1_arg);
	result_1 = req_1(&req_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("Result:%f\n",*result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 3) {
		printf ("usage: %s server_host, URL\n", argv[0]);
		exit (1);
	}
	
	
	printf("connected to server!\n");
	
	host = argv[1];
	http_req_1 (host, argv[2]);
	printf("This is the value of url which client enter : %s\n",argv[2]);
	
exit (0);
}
