/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "res.h"
#include <curl/curl.h>

int *
req_1_svc(response *argp, struct svc_req *rqstp)
{
	static int result;

	/*
	 * insert server code here
	 */
	printf("connected to client!\n");
	
    	CURL *curl;
    	CURLcode response;
	 
    	curl_global_init(CURL_GLOBAL_ALL);
	
	
    	curl = curl_easy_init();
    	if(curl) {
        	curl_easy_setopt(curl, CURLOPT_URL, argp->url);
        	
		printf("this is the value of argv->url : %s\n",argp->url);
        	response = curl_easy_perform(curl);
		
		
		if(response != CURLE_OK) {
		    fprintf(stderr, "Request failed: %s\n", curl_easy_strerror(response));
		} else {
		    result = printf("%s\n",response);
		}
		curl_easy_cleanup(curl);
	 }
	 curl_global_cleanup();	

	return &result;
}
